//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioDevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioDevice
    {
        public int SerialId { get; set; }
        public string Model { get; set; }
        public string Make { get; set; }
        public decimal PriceExBtw { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal BtwPrecentage { get; set; }
    
        public virtual CdDiskMan CdDiskMan { get; set; }
        public virtual MemoRecorder MemoRecorder { get; set; }
        public virtual Mp3Player Mp3Player { get; set; }
    }
}
